//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahdyar_Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mahdyar_Library.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی لازم به این قسمت را ندارید.
        /// </summary>
        public static string AccessIsDenied {
            get {
                return ResourceManager.GetString("AccessIsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسمبلی مورد نظر یافت نشد.
        /// </summary>
        public static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پردازش اطلاعات.
        /// </summary>
        public static string CommonError {
            get {
                return ResourceManager.GetString("CommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در به روز رسانی اطلاعات رخ داده است.
        /// </summary>
        public static string DataUpdateError {
            get {
                return ResourceManager.GetString("DataUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خـطای امنیتی، شـما اجازه حذف اطلاعات را ندارید.
        /// </summary>
        public static string DeleteSecurityError {
            get {
                return ResourceManager.GetString("DeleteSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پـسـت الکـترونیـکی وارد شده تکراری است.
        /// </summary>
        public static string DuplicateEmailError {
            get {
                return ResourceManager.GetString("DuplicateEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نـام کاربری وارد شده تکراری است.
        /// </summary>
        public static string DuplicateUsernameError {
            get {
                return ResourceManager.GetString("DuplicateUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خـطای امنیتی، شـما اجازه درج اطلاعات را ندارید.
        /// </summary>
        public static string InsertSecurityError {
            get {
                return ResourceManager.GetString("InsertSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور اشتباه است..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نـام کاربری و یا کلمه عبور شما معتبر نیست.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصیصه کلید پیدا نشد.
        /// </summary>
        public static string KeyPropertyNotFoundError {
            get {
                return ResourceManager.GetString("KeyPropertyNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه خطایی در سیستم رخ داده است، لطفاً با تیم پشتیبانی تماس بگیرید.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خـطای امنیتی، شـما اجازه ویرایش ندارید.
        /// </summary>
        public static string UpdateSecurityError {
            get {
                return ResourceManager.GetString("UpdateSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین کاربری در سیستم وجود ندارد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اعتبار سنجی اطلاعات.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
